// Ordered most-specific first so "bell pepper" matches before "pepper"
const ITEM_EMOJI_PAIRS: [string[], string][] = [
  // Specific-first guards (must stay above generic entries)
  [['sugar scrub', 'body scrub', 'exfoliating scrub'], '🧴'],
  [['ice cream', 'gelato', 'sorbet', 'frozen yogurt', 'popsicle'], '🍦'],
  [['lentil', 'lentils', 'red lentil', 'green lentil', 'french lentil', 'beluga lentil', 'black lentil', 'split pea lentil'], '🫘'],
  [['raisin', 'raisins', 'golden raisin', 'black raisin', 'sultana'], '🍇'],
  [['sour cream', 'crème fraîche', 'creme fraiche'], '🥛'],
  [['greek yogurt', 'yogurt', 'yoghurt', 'skyr'], '🥛'],
  [['cottage cheese'], '🧀'],
  [['heavy cream', 'whipping cream', 'half and half', 'table cream', 'cooking cream'], '🥛'],
  [['sugar', 'brown sugar', 'powdered sugar', 'icing sugar', 'raw sugar', 'caster sugar', 'demerara', 'turbinado', 'granulated sugar', 'white sugar'], '🍬'],
  [['chickpea', 'garbanzo', 'chickpeas'], '🫘'],
  [['peanut butter', 'almond butter', 'cashew butter', 'nut butter'], '🥜'],
  [['soy sauce', 'tamari', 'teriyaki sauce', 'fish sauce', 'worcestershire'], '🫙'],

  // Vegetables (specific first)
  [['bell pepper', 'capsicum'], '🫑'],
  [['hot pepper', 'chili pepper', 'chilli pepper', 'jalapeño', 'jalapeno', 'habanero', 'serrano'], '🌶️'],
  [['sweet potato', 'yam'], '🍠'],
  [['sugar snap pea', 'snap pea', 'snow pea'], '🫛'],
  [['broccoli'], '🥦'],
  [['carrot'], '🥕'],
  [['corn', 'maize'], '🌽'],
  [['cucumber'], '🥒'],
  [['eggplant', 'aubergine'], '🍆'],
  [['garlic'], '🧄'],
  [['kale', 'chard', 'arugula', 'rocket'], '🥬'],
  [['lettuce', 'romaine', 'iceberg'], '🥬'],
  [['mushroom'], '🍄'],
  [['onion', 'shallot', 'leek'], '🧅'],
  [['pea', 'edamame'], '🫛'],
  [['pepper', 'chili', 'chilli', 'paprika'], '🌶️'],
  [['potato'], '🥔'],
  [['pumpkin seed', 'pepita'], '🌱'],
  [['pumpkin', 'squash', 'zucchini', 'courgette'], '🎃'],
  [['spinach'], '🥬'],
  [['tomato', 'cherry tom'], '🍅'],
  [['avocado'], '🥑'],
  [['celery'], '🥬'],
  [['asparagus'], '🥦'],
  [['cabbage', 'brussels'], '🥬'],
  [['cauliflower'], '🥦'],
  [['beet', 'beetroot', 'radish', 'turnip'], '🥕'],
  [['artichoke'], '🥦'],
  [['bean sprout', 'sprout', 'microgreen'], '🌱'],
  [['ginger', 'fresh ginger', 'ginger root'], '🫚'],
  [['fennel'], '🌿'],
  [['parsnip'], '🥕'],
  [['celeriac', 'celery root'], '🥬'],
  [['bok choy', 'pak choi', 'napa cabbage', 'chinese cabbage', 'chinese broccoli', 'gai lan'], '🥬'],
  [['okra'], '🫛'],
  [['corn on the cob', 'sweet corn'], '🌽'],
  [['scallion', 'green onion', 'spring onion'], '🧅'],
  [['watercress', 'endive', 'radicchio', 'escarole'], '🥬'],
  [['butternut', 'acorn squash', 'spaghetti squash', 'delicata'], '🎃'],
  [['artichoke heart'], '🥦'],

  // Fruits (specific first)
  [['blood orange'], '🍊'],
  [['strawberry', 'strawberries'], '🍓'],
  [['raspberry', 'raspberries'], '🍓'],
  [['blueberry', 'blueberries', 'blackberry', 'blackberries'], '🫐'],
  [['watermelon'], '🍉'],
  [['pineapple'], '🍍'],
  [['kiwi', 'kiwifruit'], '🥝'],
  [['mango'], '🥭'],
  [['coconut'], '🥥'],
  [['apple'], '🍎'],
  [['banana'], '🍌'],
  [['cherry', 'cherries'], '🍒'],
  [['grape'], '🍇'],
  [['lemon'], '🍋'],
  [['lime'], '🍋'],
  [['orange', 'clementine', 'mandarin', 'tangerine'], '🍊'],
  [['peach', 'nectarine'], '🍑'],
  [['pear'], '🍐'],
  [['plum', 'prune'], '🍑'],
  [['fig'], '🍑'],
  [['melon', 'cantaloupe', 'honeydew'], '🍈'],
  [['pomegranate'], '🍎'],
  [['date', 'medjool'], '🍑'],
  [['apricot', 'dried apricot'], '🍑'],
  [['cranberry', 'cranberries', 'dried cranberry', 'craisin'], '🍓'],
  [['currant', 'gooseberry'], '🍇'],
  [['passion fruit', 'passionfruit', 'dragon fruit', 'dragonfruit', 'guava', 'papaya'], '🍑'],
  [['lychee', 'longan', 'jackfruit', 'durian'], '🍑'],
  [['persimmon', 'quince'], '🍑'],

  // Proteins (specific first)
  // Note: shampoo/conditioner guard — these must come before bare 'ham' to win substring match
  [['shampoo', 'conditioner'], '🧴'],
  [['ground beef', 'minced beef', 'hamburger meat', 'beef mince'], '🥩'],
  [['chicken breast', 'chicken thigh', 'chicken wing', 'chicken drumstick'], '🍗'],
  [['pork chop', 'pork loin', 'pork belly', 'pulled pork'], '🥩'],
  [['hot dog', 'hotdog', 'frankfurter'], '🌭'],
  [['sausage', 'bratwurst', 'chorizo', 'salami', 'pepperoni'], '🌭'],
  [['bacon'], '🥓'],
  [['beef', 'steak', 'brisket', 'ribs', 'ribeye', 'sirloin'], '🥩'],
  [['chicken', 'poultry'], '🍗'],
  [['duck', 'goose'], '🍗'],
  [['egg', 'eggs'], '🥚'],
  [['fish oil', 'omega 3', 'omega-3', 'cod liver oil', 'krill oil'], '💊'],
  [['fish', 'cod', 'tilapia', 'bass', 'halibut', 'snapper'], '🐟'],
  [['ham', 'prosciutto', 'pancetta', 'jambon'], '🍖'],
  [['lamb', 'mutton'], '🍖'],
  [['lobster', 'crab', 'crayfish'], '🦞'],
  [['pork'], '🥩'],
  [['salmon'], '🐟'],
  [['shrimp', 'prawn'], '🍤'],
  [['tofu', 'tempeh', 'seitan'], '🫙'],
  [['anchovie', 'anchovy', 'sardine', 'herring', 'mackerel'], '🐟'],
  [['clam', 'mussel', 'oyster', 'scallop', 'squid', 'octopus'], '🦪'],
  [['venison', 'bison', 'rabbit'], '🥩'],
  [['tuna'], '🐟'],
  [['turkey'], '🦃'],

  // Dairy (specific first)
  [['almond milk', 'oat milk', 'soy milk', 'coconut milk', 'plant milk'], '🥛'],
  [['sour cream', 'crème fraîche', 'creme fraiche'], '🫙'],
  [['cream cheese', 'ricotta', 'mascarpone', 'brie', 'camembert', 'feta', 'gouda', 'cheddar', 'mozzarella', 'parmesan', 'gruyere', 'swiss cheese'], '🧀'],
  [['cottage cheese'], '🥣'],
  [['butter', 'ghee', 'margarine'], '🧈'],
  [['cheese'], '🧀'],
  [['cream', 'whipping cream', 'heavy cream', 'half and half'], '🥣'],
  [['milk'], '🥛'],
  [['yogurt', 'yoghurt', 'greek yogurt'], '🥣'],
  [['kefir'], '🥛'],
  [['condensed milk', 'evaporated milk'], '🥛'],
  [['coconut cream', 'coconut milk'], '🥥'],
  [['powdered milk', 'dry milk', 'milk powder'], '🥛'],
  [['lactose free milk', 'lactose-free milk'], '🥛'],

  // Grains & Baked Goods (specific first)
  [['sourdough', 'baguette', 'ciabatta', 'focaccia'], '🥖'],
  [['pita', 'flatbread', 'naan', 'roti', 'chapati'], '🫓'],
  [['tortilla', 'wrap', 'burrito wrap'], '🌯'],
  [['bagel'], '🥯'],
  [['bread', 'loaf', 'bun', 'roll', 'toast'], '🍞'],
  [['cereal', 'granola', 'muesli'], '🥣'],
  [['cookie', 'biscuit', 'oreo'], '🍪'],
  [['cracker', 'rice cake'], '🍘'],
  [['croissant'], '🥐'],
  [['donut', 'doughnut'], '🍩'],
  [['flour', 'cornstarch', 'cornflour', 'baking powder', 'baking soda'], '🌾'],
  [['muffin', 'cupcake'], '🧁'],
  [['noodle', 'ramen', 'udon', 'soba', 'vermicelli'], '🍜'],
  [['oat', 'oatmeal', 'porridge'], '🥣'],
  [['pancake', 'waffle'], '🥞'],
  [['pasta', 'spaghetti', 'linguine', 'fettuccine', 'penne', 'rigatoni', 'fusilli', 'macaroni', 'lasagna'], '🍝'],
  [['popcorn'], '🍿'],
  [['pretzel'], '🥨'],
  [['rice', 'basmati', 'jasmine rice', 'brown rice', 'wild rice'], '🍚'],
  [['quinoa', 'couscous', 'bulgur', 'barley', 'farro', 'millet', 'amaranth', 'teff', 'spelt', 'kamut', 'freekeh'], '🌾'],
  [['polenta', 'cornmeal', 'grits'], '🌽'],
  [['semolina', 'almond flour', 'coconut flour', 'chickpea flour', 'rice flour', 'tapioca'], '🌾'],
  [['bread crumb', 'breadcrumb', 'panko'], '🍞'],
  [['yeast', 'active dry yeast', 'instant yeast'], '🌾'],
  [['corn syrup', 'golden syrup', 'molasses'], '🍯'],

  // Condiments & Pantry Staples (specific first)
  [['hot sauce', 'sriracha', 'tabasco', 'buffalo sauce', 'frank\'s'], '🌶️'],
  [['peanut butter', 'almond butter', 'cashew butter', 'nut butter'], '🥜'],
  [['olive oil', 'vegetable oil', 'canola oil', 'coconut oil', 'sesame oil', 'sunflower oil'], '🫒'],
  [['soy sauce', 'tamari', 'teriyaki sauce', 'fish sauce', 'worcestershire'], '🥢'],
  [['tomato sauce', 'marinara', 'pasta sauce', 'tomato paste', 'tomato purée'], '🍅'],
  [['ketchup', 'catsup'], '🍅'],
  [['mayonnaise', 'mayo', 'aioli'], '🫙'],
  [['mustard', 'dijon'], '🫙'],
  [['salsa', 'guacamole', 'hummus'], '🫙'],
  [['dressing', 'vinaigrette', 'ranch', 'caesar dressing'], '🫙'],
  [['jam', 'jelly', 'marmalade', 'preserve', 'compote'], '🍯'],
  [['honey', 'agave', 'maple syrup'], '🍯'],
  [['nutella', 'hazelnut spread', 'chocolate spread'], '🍫'],
  [['oil'], '🫒'],
  [['vinegar', 'balsamic'], '🫙'],
  [['salt'], '🧂'],
  [['pepper', 'black pepper', 'white pepper', 'peppercorn'], '🧂'],
  [['spice', 'cumin', 'turmeric', 'cinnamon', 'nutmeg', 'cardamom', 'clove', 'allspice', 'sumac', 'za\'atar'], '🌿'],
  [['herb', 'basil', 'oregano', 'thyme', 'rosemary', 'parsley', 'cilantro', 'dill', 'mint', 'sage', 'tarragon', 'chive'], '🌿'],
  [['vanilla', 'extract'], '🫙'],
  [['sugar', 'brown sugar', 'powdered sugar', 'icing sugar', 'raw sugar', 'caster sugar', 'demerara', 'turbinado'], '🧂'],
  [['tahini', 'sesame paste'], '🫙'],
  [['miso', 'miso paste'], '🫙'],
  [['harissa', 'gochujang', 'doubanjiang', 'sambal'], '🌶️'],
  [['curry paste', 'red curry', 'green curry', 'yellow curry'], '🌶️'],
  [['oyster sauce', 'hoisin', 'plum sauce', 'sweet chili sauce'], '🫙'],
  [['coconut aminos', 'liquid aminos'], '🫙'],
  [['rice vinegar', 'apple cider vinegar', 'white wine vinegar', 'red wine vinegar', 'sherry vinegar'], '🫙'],
  [['lemon juice', 'lime juice'], '🍋'],
  [['nutritional yeast', 'nooch'], '🌿'],
  [['cocoa powder', 'cacao powder', 'cacao nibs', 'cocoa'], '🍫'],
  [['cream of tartar'], '🌾'],
  [['avocado oil'], '🥑'],
  [['truffle oil', 'chili oil', 'infused oil'], '🫒'],
  [['shortening', 'lard', 'beef tallow', 'duck fat'], '🧈'],
  [['cooking spray', 'non-stick spray', 'canola spray', 'avocado spray', 'olive spray', 'baking spray'], '🫒'],
  [['salt and pepper', 'seasoning'], '🧂'],
  [['garlic salt', 'garlic powder', 'onion powder', 'celery salt'], '🧂'],
  [['chili powder', 'cayenne', 'red pepper flake', 'crushed red pepper', 'ancho', 'chipotle powder'], '🌶️'],
  [['curry powder', 'garam masala', 'ras el hanout', 'baharat', 'five spice', 'berbere'], '🌿'],
  [['smoked paprika', 'sweet paprika'], '🌶️'],
  [['dried ginger', 'ground ginger'], '🫚'],
  [['matcha', 'matcha powder'], '🍵'],
  [['coffee bean', 'ground coffee', 'instant coffee', 'coffee pod', 'k-cup', 'nespresso'], '☕'],

  // Beverages (specific first)
  [['sparkling water', 'mineral water', 'soda water', 'club soda', 'tonic water', 'perrier', 'la croix'], '💧'],
  [['orange juice', 'apple juice', 'grape juice', 'cranberry juice', 'pineapple juice'], '🧃'],
  [['energy drink', 'red bull', 'monster'], '🥤'],
  [['iced tea', 'sweet tea'], '🧃'],
  [['beer', 'ale', 'lager', 'stout', 'ipa'], '🍺'],
  [['coffee', 'espresso', 'cold brew', 'latte'], '☕'],
  [['juice', 'lemonade', 'smoothie'], '🧃'],
  [['kombucha'], '🧃'],
  [['milk'], '🥛'],
  [['soda', 'cola', 'pop', 'coke', 'pepsi', 'sprite', 'fanta', 'dr pepper'], '🥤'],
  [['tea', 'green tea', 'herbal tea', 'chai'], '🍵'],
  [['water'], '💧'],
  [['wine', 'champagne', 'prosecco', 'rosé', 'rose wine'], '🍷'],
  [['spirits', 'whiskey', 'vodka', 'rum', 'gin', 'tequila', 'brandy', 'bourbon'], '🥃'],
  [['sake', 'mirin', 'rice wine'], '🍶'],
  [['cider', 'hard cider'], '🍺'],
  [['hot chocolate', 'cocoa mix', 'drinking chocolate'], '🍫'],
  [['protein shake', 'meal replacement shake'], '🥛'],

  // Snacks & Sweets (specific first)
  [['ice cream', 'gelato', 'sorbet', 'frozen yogurt', 'popsicle'], '🍦'],
  [['chocolate chip', 'dark chocolate', 'milk chocolate', 'white chocolate'], '🍫'],
  [['candy bar', 'candy', 'sweets', 'lolly', 'gummy bear', 'gummy', 'gummies', 'licorice'], '🍬'],
  [['chip', 'crisp', 'nacho', 'tortilla chip', 'potato chip'], '🍟'],
  [['chocolate'], '🍫'],
  [['cake', 'cheesecake', 'pound cake'], '🎂'],
  [['brownie'], '🍫'],
  [['nut', 'almond', 'cashew', 'walnut', 'pecan', 'pistachio', 'macadamia', 'hazelnut', 'pine nut', 'brazil nut', 'chestnut'], '🥜'],
  [['peanut', 'groundnut'], '🥜'],
  [['seed', 'chia seed', 'flax seed', 'flaxseed', 'hemp seed', 'sesame seed', 'sunflower seed', 'poppy seed'], '🌱'],
  [['trail mix', 'mixed nut', 'nut mix'], '🥜'],
  [['pretzel'], '🥨'],
  [['protein bar', 'granola bar', 'energy bar', 'snack bar', 'cereal bar', 'kind bar', 'larabar'], '🫙'],
  [['dried mango', 'dried pineapple', 'dried banana chip', 'dried fig', 'dried cherry'], '🍑'],
  [['fruit leather', 'fruit snack', 'gummy fruit', 'dried fruit'], '🍑'],
  [['rice cracker', 'rice puff'], '🫙'],
  [['jello', 'gelatin', 'pudding mix'], '🍮'],

  // Canned & Packaged (specific first)
  [['canned tomato', 'crushed tomato', 'diced tomato', 'whole tomato'], '🥫'],
  [['canned bean', 'canned chickpea', 'canned lentil', 'canned corn'], '🥫'],
  [['canned tuna', 'canned salmon', 'canned sardine', 'canned fish'], '🥫'],
  [['canned', 'can of'], '🥫'],
  [['chickpea', 'garbanzo'], '🫘'],
  [['lentil', 'red lentil', 'green lentil', 'french lentil', 'beluga lentil', 'black lentil'], '🥣'],
  [['bean', 'legume', 'kidney bean', 'black bean', 'navy bean', 'cannellini', 'pinto bean', 'adzuki', 'fava', 'broad bean', 'lima bean', 'butter bean', 'black-eyed pea', 'split pea'], '🫘'],
  [['nori', 'seaweed', 'kelp', 'wakame', 'dulse', 'spirulina'], '🌿'],
  [['mung bean', 'dal', 'dhal', 'daal'], '🫘'],

  // Frozen Foods (specific first)
  [['frozen pizza'], '🍕'],
  [['frozen meal', 'tv dinner', 'frozen dinner', 'frozen burrito'], '🍱'],
  [['frozen veg', 'frozen peas', 'frozen corn', 'frozen broccoli', 'frozen spinach'], '🥦'],
  [['frozen fruit', 'frozen berries', 'frozen mango'], '🍓'],
  [['frozen fries', 'french fries', 'potato fries'], '🍟'],

  // International & specialty
  [['pasta sauce', 'arrabiata', 'puttanesca', 'bolognese sauce'], '🍅'],
  [['ramen noodle', 'instant noodle', 'cup noodle', 'instant ramen'], '🍜'],
  [['rice noodle', 'glass noodle', 'cellophane noodle', 'pad thai noodle'], '🍜'],
  [['gyoza wrapper', 'dumpling wrapper', 'wonton wrapper', 'spring roll wrapper'], '🥟'],
  [['tofu skin', 'aburaage'], '🫙'],
  [['paneer'], '🧀'],
  [['halloumi'], '🧀'],
  [['labneh'], '🧀'],
  [['kimchi'], '🥬'],
  [['sauerkraut', 'fermented cabbage'], '🥬'],
  [['pickles', 'pickle', 'gherkin', 'cornichon', 'pickled'], '🫙'],
  [['capers'], '🫙'],
  [['anchovie paste', 'tomato paste tube'], '🫙'],
  [['sun dried tomato', 'sun-dried tomato'], '🍅'],
  [['artichoke heart', 'roasted pepper'], '🥫'],
  [['olive', 'kalamata', 'green olive', 'black olive'], '🫒'],
  [['pine apple chunk', 'canned pineapple', 'canned peach', 'canned pear', 'canned cherry'], '🥫'],

  // ── Paper & disposables ─────────────────────────────────────────────────────
  [['toilet paper', 'tp', 'bathroom tissue', 'charmin', 'angel soft', 'cottonelle', 'scott tissue'], '🧻'],
  [['paper towel', 'kitchen roll', 'bounty', 'brawny', 'viva', 'select-a-size'], '🧻'],
  [['facial tissue', 'kleenex', 'puffs', 'tissue box'], '🧻'],
  [['napkin', 'paper napkin', 'dinner napkin'], '🧻'],
  [['paper plate', 'foam plate', 'dixie plate', 'chinet'], '🍽️'],
  [['paper cup', 'plastic cup', 'solo cup', 'disposable cup'], '🥤'],
  [['plastic utensil', 'plastic fork', 'plastic spoon', 'plastic knife', 'disposable cutlery'], '🍴'],
  [['aluminum foil', 'tin foil', 'reynolds wrap', 'heavy duty foil'], '🫙'],
  [['plastic wrap', 'cling wrap', 'saran wrap', 'cling film'], '🫙'],
  [['parchment paper', 'wax paper', 'baking paper', 'butcher paper'], '🫙'],
  [['zip lock', 'ziplock', 'ziploc', 'sandwich bag', 'snack bag', 'freezer bag', 'storage bag', 'glad bag', 'hefty bag'], '🫙'],
  [['trash bag', 'garbage bag', 'bin bag', 'bin liner', 'kitchen bag', 'contractor bag', 'glad forceflex', 'hefty ultra'], '🗑️'],
  [['foil pan', 'disposable pan', 'roasting pan disposable'], '🫙'],
  [['coffee filter', 'paper filter', 'k-cup filter'], '☕'],
  [['straw', 'paper straw', 'reusable straw'], '🥤'],

  // ── Cleaning ────────────────────────────────────────────────────────────────
  [['all purpose cleaner', 'multi surface cleaner', '409', 'fantastik', 'pine-sol', 'fabuloso', 'mr. clean', 'lysol spray'], '🧽'],
  [['glass cleaner', 'window cleaner', 'windex', 'method glass'], '🧽'],
  [['bathroom cleaner', 'tub cleaner', 'tile cleaner', 'scrubbing bubbles', 'comet'], '🧽'],
  [['toilet bowl cleaner', 'toilet cleaner', 'lysol toilet', 'bowl cleaner'], '🧽'],
  [['floor cleaner', 'floor cleaner', 'mop solution', 'bona', 'murphy oil soap', 'pledge floor'], '🧽'],
  [['bleach', 'clorox bleach', 'concentrated bleach', 'splash-less bleach'], '🧽'],
  [['disinfectant', 'disinfecting wipe', 'clorox wipe', 'lysol wipe', 'antibacterial wipe'], '🧽'],
  [['dish soap', 'dish detergent', 'dawn', 'palmolive', 'seventh generation dish', 'ajax dish'], '🧼'],
  [['dishwasher pod', 'dishwasher tab', 'dishwasher detergent', 'cascade pod', 'finish tab', 'cascade complete'], '🧼'],
  [['dishwasher rinse aid', 'jet dry', 'rinse aid'], '🧼'],
  [['sponge', 'scrubber', 'scotch brite', 'o-cel-o', 'dish sponge', 'scrub pad'], '🧽'],
  [['rubber glove', 'cleaning glove', 'latex glove', 'nitrile glove'], '🧤'],
  [['mop', 'swiffer', 'swifter', 'mop refill', 'wet jet'], '🧹'],
  [['broom', 'dustpan', 'sweep'], '🧹'],
  [['vacuum bag', 'vacuum filter', 'robot vacuum'], '🧹'],
  [['air freshener', 'febreze', 'glade spray', 'ozium', 'room spray', 'linen spray'], '🌸'],
  [['plug-in refill', 'glade plugin', 'febreze plug', 'air wick refill'], '🌸'],
  [['dryer ball', 'wool dryer ball', 'clean ball'], '🧺'],

  // ── Laundry ──────────────────────────────────────────────────────────────────
  [['laundry detergent', 'washing powder', 'tide', 'gain detergent', 'persil', 'arm & hammer detergent', 'all detergent', 'cheer', 'xtra detergent'], '🧺'],
  [['fabric softener', 'downy', 'snuggle', 'gain softener', 'bounce fabric'], '🧺'],
  [['dryer sheet', 'bounce sheet', 'gain dryer', 'snuggle sheet'], '🧺'],
  [['stain remover', 'oxiclean', 'shout', 'zout', 'spray n wash', 'tide to go', 'carbona'], '🧺'],
  [['laundry pod', 'tide pod', 'gain flings', 'all mighty pacs'], '🧺'],
  [['bleach pen', 'clorox pen'], '🧺'],
  [['mesh laundry bag', 'hamper liner'], '🧺'],

  // ── Personal care — hair ─────────────────────────────────────────────────────
  [['shampoo', 'head & shoulders', 'pantene shampoo', 'herbal essence shampoo', 'dove shampoo', 'suave shampoo', 'tresemme shampoo', 'ogx shampoo', 'garnier shampoo'], '🧴'],
  [['conditioner', 'hair conditioner', 'pantene conditioner', 'tresemme conditioner', 'dove conditioner', 'ogx conditioner'], '🧴'],
  [['2-in-1 shampoo', 'shampoo and conditioner'], '🧴'],
  [['dry shampoo', 'batiste', 'not your mothers dry shampoo'], '🧴'],
  [['hair mask', 'deep conditioner', 'hair treatment', 'hair oil', 'argan oil hair'], '🧴'],
  [['hair gel', 'hair mousse', 'hair spray', 'got2b', 'tresemme spray', 'kenra', 'garnier fructis gel'], '🧴'],
  [['hair dye', 'hair color', 'root touch up', 'box dye', 'clairol', 'loreal hair color', 'garnier nutrisse'], '🧴'],
  [['heat protectant', 'hair serum', 'frizz control', 'chi silk infusion'], '🧴'],
  [['comb', 'hair brush', 'detangling brush', 'paddle brush', 'wide tooth comb'], '🪮'],
  [['hair tie', 'scrunchie', 'hair band', 'bobby pin', 'hair clip', 'barrette'], '💇'],
  [['hair net', 'shower cap'], '💇'],

  // ── Personal care — skin ─────────────────────────────────────────────────────
  [['body wash', 'shower gel', 'dove body wash', 'old spice body wash', 'olay body wash', 'nivea body wash', 'irish spring body wash'], '🧴'],
  [['bar soap', 'dove bar', 'irish spring', 'dial soap', 'ivory soap', 'zest bar', 'dr. bronner', 'castile soap'], '🧼'],
  [['hand soap', 'liquid hand soap', 'softsoap', 'method hand soap', 'purell soap', 'dial hand soap'], '🧼'],
  [['hand sanitizer', 'purell', 'germ-x', 'alcohol gel', 'sanitizer spray'], '🧴'],
  [['lotion', 'body lotion', 'moisturizer', 'cetaphil lotion', 'lubriderm', 'vaseline lotion', 'aveeno lotion', 'jergens', 'curel', 'gold bond'], '🧴'],
  [['face wash', 'facial cleanser', 'cerave cleanser', 'neutrogena face wash', 'olay cleanser', 'cetaphil cleanser', 'clean & clear'], '🧴'],
  [['face moisturizer', 'face cream', 'spf moisturizer', 'cerave moisturizer', 'olay regenerist', 'neutrogena hydro boost'], '🧴'],
  [['sunscreen', 'spf', 'sun block', 'coppertone', 'banana boat', 'neutrogena spf', 'hawaiian tropic', 'sport sunscreen', 'kids sunscreen'], '🌞'],
  [['lip balm', 'chapstick', 'carmex', 'burt\'s bees lip', 'vaseline lip', 'eos lip'], '💄'],
  [['vaseline', 'petroleum jelly', 'aquaphor'], '🧴'],
  [['eye cream', 'under eye patch', 'dark circle cream'], '🧴'],
  [['toner', 'micellar water', 'witch hazel', 'rose water'], '🧴'],
  [['serum', 'vitamin c serum', 'retinol', 'hyaluronic acid serum', 'niacinamide'], '🧴'],
  [['face mask', 'sheet mask', 'clay mask', 'peel off mask'], '🧴'],
  [['exfoliant', 'scrub', 'exfoliating wash', 'st. ives scrub', 'sugar scrub'], '🧴'],
  [['self tanner', 'tanning lotion', 'after sun lotion', 'aloe vera gel'], '🧴'],
  [['cotton ball', 'cotton round', 'makeup remover pad'], '💊'],
  [['makeup wipe', 'face wipe', 'neutrogena makeup wipe', 'pond\'s wipe', 'simple wipe'], '🧻'],
  [['q-tip', 'cotton swab', 'cotton bud'], '💊'],
  [['razor', 'disposable razor', 'gillette', 'venus razor', 'bic razor', 'schick', 'harry\'s razor'], '🪒'],
  [['razor blade', 'refill cartridge', 'gillette refill', 'venus refill'], '🪒'],
  [['shaving cream', 'shaving gel', 'edge shaving', 'barbasol', 'gillette foam'], '🪒'],
  [['aftershave', 'after shave lotion'], '🪒'],
  [['deodorant', 'antiperspirant', 'old spice', 'dove deodorant', 'secret deodorant', 'degree deodorant', 'speed stick', 'arm & hammer deodorant', 'native deodorant'], '🧴'],
  [['body spray', 'cologne spray', 'axe body spray', 'impulse body spray'], '🧴'],
  [['perfume', 'cologne', 'eau de toilette', 'fragrance'], '🌸'],

  // ── Personal care — dental ───────────────────────────────────────────────────
  [['toothpaste', 'crest', 'colgate', 'sensodyne', 'arm & hammer toothpaste', 'whitening toothpaste', 'kids toothpaste'], '🪥'],
  [['toothbrush', 'electric toothbrush', 'oral-b toothbrush', 'colgate toothbrush', 'spinbrush'], '🪥'],
  [['dental floss', 'floss pick', 'reach floss', 'oral-b floss', 'glide floss', 'waterpik'], '🪥'],
  [['mouthwash', 'listerine', 'scope mouthwash', 'act mouthwash', 'crest mouthwash'], '🪥'],
  [['whitening strip', 'crest whitestrip', 'teeth whitening'], '🪥'],
  [['denture tablet', 'denture adhesive', 'fixodent', 'poligrip'], '🪥'],

  // ── Personal care — feminine ─────────────────────────────────────────────────
  [['tampon', 'tampax', 'playtex tampon', 'o.b. tampon', 'organic tampon'], '🌸'],
  [['pad', 'maxi pad', 'always pad', 'kotex pad', 'stayfree pad', 'overnight pad', 'pantyliner', 'panty liner', 'carefree liner'], '🌸'],
  [['menstrual cup', 'period cup', 'diva cup'], '🌸'],
  [['period underwear', 'thinx'], '🌸'],

  // ── Health & medicine ────────────────────────────────────────────────────────
  [['pain reliever', 'ibuprofen', 'advil', 'motrin', 'acetaminophen', 'tylenol', 'aspirin', 'bayer aspirin', 'aleve', 'naproxen'], '💊'],
  [['cold medicine', 'nyquil', 'dayquil', 'theraflu', 'robitussin', 'mucinex', 'coricidin', 'sudafed'], '💊'],
  [['allergy medicine', 'zyrtec', 'claritin', 'allegra', 'benadryl', 'loratadine', 'cetirizine', 'antihistamine'], '💊'],
  [['antacid', 'tums', 'rolaids', 'pepto bismol', 'mylanta', 'omeprazole', 'prilosec', 'nexium', 'zantac', 'pepcid', 'gaviscon'], '💊'],
  [['laxative', 'stool softener', 'miralax', 'colace', 'dulcolax', 'senokot', 'fiber supplement'], '💊'],
  [['cough drop', 'halls', 'ricola', 'fisherman\'s friend', 'luden\'s', 'throat lozenge'], '🍬'],
  [['cough syrup', 'robitussin dm', 'delsym', 'mucinex dm', 'honey cough'], '💊'],
  [['nasal spray', 'flonase', 'nasacort', 'afrin', 'neti pot', 'saline spray'], '💊'],
  [['eye drop', 'visine', 'clear eyes', 'artificial tears', 'zaditor', 'lumify'], '💊'],
  [['first aid kit', 'bandage', 'band-aid', 'neosporin', 'antibiotic ointment', 'gauze', 'medical tape', 'ace bandage'], '🩹'],
  [['thermometer', 'blood pressure monitor', 'pulse oximeter', 'glucose meter', 'test strip'], '🌡️'],
  [['melatonin', 'sleep aid', 'zzzquil', 'unisom', 'simply sleep'], '💊'],
  [['probiotic', 'culturelle', 'align probiotic', 'acidophilus', 'kombucha probiotic'], '💊'],
  [['vitamin', 'multivitamin', 'centrum', 'one a day', 'flintstones vitamin', 'gummy vitamin', 'prenatal vitamin'], '💊'],
  [['vitamin c', 'emergen-c', 'vitamin d', 'vitamin b12', 'vitamin b complex', 'vitamin e', 'vitamin k', 'vitamin a'], '💊'],
  [['zinc', 'magnesium supplement', 'calcium supplement', 'iron supplement', 'potassium supplement'], '💊'],
  [['protein powder', 'whey', 'creatine', 'pre-workout', 'bcaa', 'protein shake mix', 'mass gainer'], '💪'],
  [['collagen', 'collagen powder', 'vital proteins'], '💊'],
  [['biotin', 'hair skin and nails', 'hair growth vitamin'], '💊'],
  [['antifungal', 'lotrimin', 'tinactin', 'lamisil', 'athlete\'s foot cream'], '💊'],
  [['hemorrhoid', 'preparation h', 'tucks pad'], '💊'],
  [['hydrocortisone', 'cortisone cream', 'anti-itch cream', 'calamine'], '💊'],
  [['wart remover', 'compound w', 'freeze away'], '💊'],
  [['nicotine patch', 'nicotine gum', 'nicorette', 'nicoderm'], '💊'],

  // ── Baby & kids ──────────────────────────────────────────────────────────────
  [['diaper', 'pampers', 'huggies', 'luvs', 'pull-up', 'nighttime diaper', 'newborn diaper', 'honest diaper'], '🍼'],
  [['baby wipe', 'diaper wipe', 'pampers wipe', 'huggies wipe', 'waterwipe', 'unscented wipe'], '🍼'],
  [['baby formula', 'infant formula', 'similac', 'enfamil', 'gerber formula', 'gentlease'], '🍼'],
  [['baby food', 'gerber puree', 'happy baby pouch', 'beech-nut', 'earth\'s best baby'], '🍼'],
  [['baby shampoo', 'johnson\'s baby', 'baby wash', 'baby lotion', 'baby powder', 'desitin', 'a+d ointment', 'aquaphor baby'], '🍼'],
  [['pacifier', 'binky', 'soother', 'mam pacifier', 'nuk pacifier'], '🍼'],
  [['baby bottle', 'dr. brown bottle', 'avent bottle', 'bottle nipple', 'sippy cup'], '🍼'],
  [['kids soap', 'bubble bath', 'kids shampoo', 'no tears shampoo'], '🧼'],
  [['diaper rash cream', 'desitin', 'butt paste', 'boudreaux'], '🍼'],
  [['children\'s tylenol', 'infant tylenol', 'children\'s advil', 'children\'s benadryl', 'kids medicine'], '💊'],
  [['pedialyte', 'rehydration drink'], '💧'],

  // ── Pet supplies ─────────────────────────────────────────────────────────────
  [['dog food', 'purina dog', 'blue buffalo dog', 'pedigree', 'iams dog', 'hills dog', 'royal canin dog', 'diamond dog', 'kibble'], '🐶'],
  [['cat food', 'purina cat', 'fancy feast', 'friskies', 'meow mix', 'blue buffalo cat', 'iams cat', 'hills cat', 'temptations cat'], '🐱'],
  [['cat litter', 'arm & hammer litter', 'tidy cats', 'fresh step', 'dr. elsey\'s', 'clumping litter', 'crystal litter'], '🐱'],
  [['pet treat', 'dog treat', 'milk bone', 'dentastix', 'beggin\' strips', 'blue bits', 'cat treat', 'temptation treat'], '🦴'],
  [['pet shampoo', 'dog shampoo', 'cat shampoo', 'flea shampoo'], '🐾'],
  [['flea medicine', 'frontline', 'advantage flea', 'seresto', 'revolution flea', 'heartgard', 'nexgard'], '🐾'],
  [['poop bag', 'dog waste bag', 'earth rated bag', 'compostable poop bag'], '🐾'],
  [['pet wipe', 'dog wipe', 'earthbath wipe'], '🐾'],
  [['aquarium food', 'fish food', 'turtle food', 'bird food', 'birdseed', 'suet cake'], '🐾'],
  [['hamster food', 'guinea pig food', 'rabbit pellet', 'chinchilla food'], '🐾'],

  // ── Kitchen supplies ─────────────────────────────────────────────────────────
  [['dish soap', 'dish detergent', 'dawn dish', 'palmolive dish', 'ajax dish', 'joy dish', 'method dish'], '🧼'],
  [['dishwasher pod', 'dishwasher tab', 'cascade', 'finish dishwasher', 'seventh gen dish'], '🧼'],
  [['garbage disposal cleaner', 'drain cleaner', 'drano', 'liquid plumr'], '🧽'],
  [['cutting board', 'plastic cutting board'], '🍽️'],
  [['plastic container', 'food storage container', 'tupperware', 'rubbermaid container'], '🫙'],
  [['reusable bag', 'grocery bag', 'produce bag', 'mesh bag'], '🛍️'],
  [['bottle brush', 'straw brush', 'pipe cleaner'], '🧽'],

  // ── Office & home misc ───────────────────────────────────────────────────────
  [['batteries', 'aa battery', 'aaa battery', 'alkaline battery', 'duracell', 'energizer', 'rayovac'], '🔋'],
  [['light bulb', 'led bulb', 'smart bulb', 'ge bulb', 'philips bulb'], '💡'],
  [['candle', 'yankee candle', 'bath & body candle', 'soy candle', 'tealight', 'pillar candle'], '🕯️'],
  [['matches', 'lighter', 'grill lighter', 'bbq lighter', 'long lighter'], '🔥'],
  [['extension cord', 'power strip', 'surge protector'], '🔌'],
  [['tape', 'scotch tape', 'packing tape', 'masking tape', 'duct tape', 'electrical tape'], '🗂️'],
  [['pen', 'ballpoint pen', 'sharpie', 'marker', 'highlighter', 'bic pen'], '🖊️'],
  [['pencil', 'mechanical pencil', 'number 2 pencil', 'eraser'], '✏️'],
  [['notebook', 'notepad', 'composition book', 'spiral notebook'], '📓'],
  [['gift bag', 'gift wrap', 'wrapping paper', 'tissue paper gift', 'ribbon', 'bow'], '🎁'],
  [['greeting card', 'birthday card', 'thank you card', 'christmas card'], '🎉'],
  [['stamps', 'postage stamp', 'usps stamp'], '✉️'],
  [['hand lotion dispenser', 'pump refill', 'soap refill'], '🧴'],

  // ── Kitchen tools & gadgets (consumable related) ─────────────────────────────
  [['toothpick', 'dental pick', 'party pick', 'skewer'], '🪥'],
  [['rubber band', 'binder clip', 'chip clip', 'bag clip', 'clothespin'], '🗂️'],

  // Misc fresh items
  [['pizza'], '🍕'],
  [['soup', 'broth', 'stock', 'bouillon'], '🍲'],
  [['salad'], '🥗'],
  [['sandwich'], '🥪'],
  [['wrap'], '🌯'],
  [['sushi', 'sashimi'], '🍱'],
  [['dip', 'spread'], '🫙'],
  [['baby food', 'infant formula'], '🍼'],
  [['supplement', 'vitamin'], '💊'],
  [['pet food', 'dog food', 'cat food', 'kibble', 'pet treat'], '🐾'],
  [['ice', 'ice cube'], '🧊'],
  [['vinaigrette bottle', 'salad dressing'], '🫙'],
  [['butter spray', 'i cant believe', 'earth balance', 'vegan butter'], '🧈'],
  [['cream puff', 'eclair', 'macaron'], '🧁'],
  [['tart', 'pie crust', 'puff pastry', 'phyllo', 'filo'], '🥐'],
];

export function getItemEmoji(name: string, _category?: string | null): string | null {
  const lower = name.toLowerCase().trim();
  for (const [keywords, emoji] of ITEM_EMOJI_PAIRS) {
    if (keywords.some((kw) => lower.includes(kw))) {
      return emoji;
    }
  }
  return null;
}
