// Ordered most-specific first so "bell pepper" matches before "pepper"
const ITEM_EMOJI_PAIRS: [string[], string][] = [
  // Vegetables (specific first)
  [['bell pepper', 'capsicum'], '🫑'],
  [['hot pepper', 'chili pepper', 'chilli pepper', 'jalapeño', 'jalapeno', 'habanero', 'serrano'], '🌶️'],
  [['sweet potato', 'yam'], '🍠'],
  [['sugar snap pea', 'snap pea', 'snow pea'], '🫛'],
  [['broccoli'], '🥦'],
  [['carrot'], '🥕'],
  [['corn', 'maize'], '🌽'],
  [['cucumber'], '🥒'],
  [['eggplant', 'aubergine'], '🍆'],
  [['garlic'], '🧄'],
  [['kale', 'chard', 'arugula', 'rocket'], '🥬'],
  [['lettuce', 'romaine', 'iceberg'], '🥬'],
  [['mushroom'], '🍄'],
  [['onion', 'shallot', 'leek'], '🧅'],
  [['pea', 'edamame'], '🫛'],
  [['pepper', 'chili', 'chilli', 'paprika'], '🌶️'],
  [['potato'], '🥔'],
  [['pumpkin', 'squash', 'zucchini', 'courgette'], '🎃'],
  [['spinach'], '🥬'],
  [['tomato', 'cherry tom'], '🍅'],
  [['avocado'], '🥑'],
  [['celery'], '🥬'],
  [['asparagus'], '🥦'],
  [['cabbage', 'brussels'], '🥬'],
  [['cauliflower'], '🥦'],
  [['beet', 'beetroot', 'radish', 'turnip'], '🥕'],
  [['artichoke'], '🥦'],
  [['bean sprout'], '🌱'],

  // Fruits (specific first)
  [['blood orange'], '🍊'],
  [['strawberry', 'strawberries'], '🍓'],
  [['raspberry', 'raspberries'], '🍓'],
  [['blueberry', 'blueberries', 'blackberry', 'blackberries'], '🫐'],
  [['watermelon'], '🍉'],
  [['pineapple'], '🍍'],
  [['kiwi', 'kiwifruit'], '🥝'],
  [['mango'], '🥭'],
  [['coconut'], '🥥'],
  [['apple'], '🍎'],
  [['banana'], '🍌'],
  [['cherry', 'cherries'], '🍒'],
  [['grape', 'raisin'], '🍇'],
  [['lemon'], '🍋'],
  [['lime'], '🍋'],
  [['orange', 'clementine', 'mandarin', 'tangerine'], '🍊'],
  [['peach', 'nectarine'], '🍑'],
  [['pear'], '🍐'],
  [['plum', 'prune'], '🍑'],
  [['fig'], '🍑'],
  [['melon', 'cantaloupe', 'honeydew'], '🍈'],
  [['pomegranate'], '🍎'],

  // Proteins (specific first)
  [['ground beef', 'minced beef', 'hamburger meat', 'beef mince'], '🥩'],
  [['chicken breast', 'chicken thigh', 'chicken wing', 'chicken drumstick'], '🍗'],
  [['pork chop', 'pork loin', 'pork belly', 'pulled pork'], '🥩'],
  [['hot dog', 'hotdog', 'frankfurter'], '🌭'],
  [['sausage', 'bratwurst', 'chorizo', 'salami', 'pepperoni'], '🌭'],
  [['bacon'], '🥓'],
  [['beef', 'steak', 'brisket', 'ribs', 'ribeye', 'sirloin'], '🥩'],
  [['chicken', 'poultry'], '🍗'],
  [['duck', 'goose'], '🍗'],
  [['egg', 'eggs'], '🥚'],
  [['fish', 'cod', 'tilapia', 'bass', 'halibut', 'snapper'], '🐟'],
  [['ham', 'prosciutto', 'pancetta'], '🍖'],
  [['lamb', 'mutton'], '🍖'],
  [['lobster', 'crab', 'crayfish'], '🦞'],
  [['pork'], '🥩'],
  [['salmon'], '🐟'],
  [['shrimp', 'prawn'], '🍤'],
  [['tofu', 'tempeh', 'seitan'], '🫙'],
  [['tuna'], '🐟'],
  [['turkey'], '🦃'],

  // Dairy (specific first)
  [['almond milk', 'oat milk', 'soy milk', 'coconut milk', 'plant milk'], '🥛'],
  [['sour cream', 'crème fraîche', 'creme fraiche'], '🥛'],
  [['cream cheese', 'ricotta', 'mascarpone', 'brie', 'camembert', 'feta', 'gouda', 'cheddar', 'mozzarella', 'parmesan', 'gruyere', 'swiss cheese'], '🧀'],
  [['cottage cheese'], '🧀'],
  [['butter', 'ghee', 'margarine'], '🧈'],
  [['cheese'], '🧀'],
  [['cream', 'whipping cream', 'heavy cream', 'half and half'], '🥛'],
  [['milk'], '🥛'],
  [['yogurt', 'yoghurt', 'greek yogurt'], '🥛'],

  // Grains & Baked Goods (specific first)
  [['sourdough', 'baguette', 'ciabatta', 'focaccia'], '🥖'],
  [['pita', 'flatbread', 'naan', 'roti', 'chapati'], '🫓'],
  [['tortilla', 'wrap', 'burrito wrap'], '🌯'],
  [['bagel'], '🥯'],
  [['bread', 'loaf', 'bun', 'roll', 'toast'], '🍞'],
  [['cereal', 'granola', 'muesli'], '🥣'],
  [['cookie', 'biscuit', 'oreo'], '🍪'],
  [['cracker', 'rice cake'], '🫙'],
  [['croissant'], '🥐'],
  [['donut', 'doughnut'], '🍩'],
  [['flour', 'cornstarch', 'cornflour', 'baking powder', 'baking soda'], '🌾'],
  [['muffin', 'cupcake'], '🧁'],
  [['noodle', 'ramen', 'udon', 'soba', 'vermicelli'], '🍜'],
  [['oat', 'oatmeal', 'porridge'], '🥣'],
  [['pancake', 'waffle'], '🥞'],
  [['pasta', 'spaghetti', 'linguine', 'fettuccine', 'penne', 'rigatoni', 'fusilli', 'macaroni', 'lasagna'], '🍝'],
  [['popcorn'], '🍿'],
  [['pretzel'], '🥨'],
  [['rice', 'basmati', 'jasmine rice', 'brown rice', 'wild rice'], '🍚'],
  [['quinoa', 'couscous', 'bulgur', 'barley', 'farro'], '🌾'],

  // Condiments & Pantry Staples (specific first)
  [['hot sauce', 'sriracha', 'tabasco', 'buffalo sauce', 'frank\'s'], '🌶️'],
  [['peanut butter', 'almond butter', 'cashew butter', 'nut butter'], '🥜'],
  [['olive oil', 'vegetable oil', 'canola oil', 'coconut oil', 'sesame oil', 'sunflower oil'], '🫒'],
  [['soy sauce', 'tamari', 'teriyaki sauce', 'fish sauce', 'worcestershire'], '🫙'],
  [['tomato sauce', 'marinara', 'pasta sauce', 'tomato paste', 'tomato purée'], '🍅'],
  [['ketchup', 'catsup'], '🍅'],
  [['mayonnaise', 'mayo', 'aioli'], '🫙'],
  [['mustard', 'dijon'], '🫙'],
  [['salsa', 'guacamole', 'hummus'], '🫙'],
  [['dressing', 'vinaigrette', 'ranch', 'caesar dressing'], '🫙'],
  [['jam', 'jelly', 'marmalade', 'preserve', 'compote'], '🍓'],
  [['honey', 'agave', 'maple syrup'], '🍯'],
  [['nutella', 'hazelnut spread', 'chocolate spread'], '🍫'],
  [['oil'], '🫒'],
  [['vinegar', 'balsamic'], '🫙'],
  [['salt'], '🧂'],
  [['pepper', 'black pepper', 'white pepper', 'peppercorn'], '🧂'],
  [['spice', 'cumin', 'turmeric', 'cinnamon', 'nutmeg', 'cardamom', 'clove', 'allspice', 'sumac', 'za\'atar'], '🌿'],
  [['herb', 'basil', 'oregano', 'thyme', 'rosemary', 'parsley', 'cilantro', 'dill', 'mint', 'sage', 'tarragon', 'chive'], '🌿'],
  [['vanilla', 'extract'], '🫙'],
  [['sugar', 'brown sugar', 'powdered sugar', 'icing sugar', 'raw sugar'], '🍬'],

  // Beverages (specific first)
  [['sparkling water', 'mineral water', 'soda water', 'club soda', 'tonic water', 'perrier', 'la croix'], '💧'],
  [['orange juice', 'apple juice', 'grape juice', 'cranberry juice', 'pineapple juice'], '🧃'],
  [['energy drink', 'red bull', 'monster'], '🥤'],
  [['iced tea', 'sweet tea'], '🧃'],
  [['beer', 'ale', 'lager', 'stout', 'ipa'], '🍺'],
  [['coffee', 'espresso', 'cold brew', 'latte'], '☕'],
  [['juice', 'lemonade', 'smoothie'], '🧃'],
  [['kombucha'], '🧃'],
  [['milk'], '🥛'],
  [['soda', 'cola', 'pop', 'coke', 'pepsi', 'sprite', 'fanta', 'dr pepper'], '🥤'],
  [['tea', 'green tea', 'herbal tea', 'chai'], '🍵'],
  [['water'], '💧'],
  [['wine', 'champagne', 'prosecco', 'rosé', 'rose wine'], '🍷'],
  [['spirits', 'whiskey', 'vodka', 'rum', 'gin', 'tequila', 'brandy', 'bourbon'], '🥃'],

  // Snacks & Sweets (specific first)
  [['ice cream', 'gelato', 'sorbet', 'frozen yogurt', 'popsicle'], '🍦'],
  [['chocolate chip', 'dark chocolate', 'milk chocolate', 'white chocolate'], '🍫'],
  [['candy bar', 'candy', 'sweets', 'lolly', 'gummy bear', 'gummy', 'gummies', 'licorice'], '🍬'],
  [['chip', 'crisp', 'nacho', 'tortilla chip', 'potato chip'], '🍟'],
  [['chocolate'], '🍫'],
  [['cake', 'cheesecake', 'pound cake'], '🎂'],
  [['brownie'], '🍫'],
  [['nut', 'almond', 'cashew', 'walnut', 'pecan', 'pistachio', 'macadamia', 'hazelnut', 'pine nut'], '🥜'],
  [['peanut', 'groundnut'], '🥜'],
  [['pretzel'], '🥨'],
  [['protein bar', 'granola bar', 'energy bar', 'snack bar'], '🫙'],

  // Canned & Packaged (specific first)
  [['canned tomato', 'crushed tomato', 'diced tomato', 'whole tomato'], '🥫'],
  [['canned bean', 'canned chickpea', 'canned lentil', 'canned corn'], '🥫'],
  [['canned tuna', 'canned salmon', 'canned sardine', 'canned fish'], '🥫'],
  [['canned', 'can of'], '🥫'],
  [['chickpea', 'garbanzo'], '🫘'],
  [['bean', 'lentil', 'legume', 'kidney bean', 'black bean', 'navy bean', 'cannellini'], '🫘'],

  // Frozen Foods (specific first)
  [['frozen pizza'], '🍕'],
  [['frozen meal', 'tv dinner', 'frozen dinner', 'frozen burrito'], '🍱'],
  [['frozen veg', 'frozen peas', 'frozen corn', 'frozen broccoli', 'frozen spinach'], '🥦'],
  [['frozen fruit', 'frozen berries', 'frozen mango'], '🍓'],
  [['frozen fries', 'french fries', 'potato fries'], '🍟'],

  // Kitchen essentials
  [['foil', 'plastic wrap', 'cling film', 'parchment', 'wax paper', 'zip lock', 'ziplock', 'sandwich bag', 'food bag'], '🫙'],
  [['dish soap', 'dish detergent', 'dishwasher tablet', 'dishwasher pod'], '🧼'],
  [['laundry', 'detergent', 'fabric softener', 'dryer sheet'], '🧺'],
  [['paper towel', 'kitchen roll', 'tissue', 'napkin'], '🧻'],
  [['toilet paper', 'tp', 'bathroom tissue'], '🧻'],
  [['trash bag', 'garbage bag', 'bin bag', 'bin liner'], '🗑️'],
  [['soap', 'hand soap', 'body wash', 'shampoo', 'conditioner'], '🧼'],
  [['toothpaste', 'toothbrush', 'floss', 'mouthwash'], '🪥'],
  [['cleaning', 'cleaner', 'bleach', 'disinfectant', 'lysol', 'windex'], '🧽'],
  [['sponge', 'scrubber'], '🧽'],

  // Misc fresh items
  [['pizza'], '🍕'],
  [['soup', 'broth', 'stock', 'bouillon'], '🍲'],
  [['salad'], '🥗'],
  [['sandwich'], '🥪'],
  [['wrap'], '🌯'],
  [['sushi', 'sashimi'], '🍱'],
  [['dip', 'spread'], '🫙'],
  [['baby food', 'infant formula'], '🍼'],
  [['protein powder', 'whey protein', 'creatine', 'supplement'], '🫙'],
];

const CATEGORY_FALLBACK: Record<string, string> = {
  fridge: '🥛',
  freezer: '🧊',
  pantry: '🧺',
};

export function getItemEmoji(name: string, category: string): string {
  const lower = name.toLowerCase().trim();
  for (const [keywords, emoji] of ITEM_EMOJI_PAIRS) {
    if (keywords.some((kw) => lower.includes(kw))) {
      return emoji;
    }
  }
  return CATEGORY_FALLBACK[category?.toLowerCase()] ?? '📦';
}
