create table public.client_crash_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  household_id uuid references public.households(id) on delete set null,
  occurred_at timestamptz not null,
  received_at timestamptz not null default now(),
  fatal boolean not null default true,
  message text not null check (length(message) <= 4000),
  stack text check (length(stack) <= 50000),
  screen text not null check (length(screen) <= 500),
  operation text not null check (length(operation) <= 500),
  sync_state jsonb not null default '{}'::jsonb check (octet_length(sync_state::text) <= 65536),
  ota_version integer not null,
  update_id uuid,
  platform text not null check (platform in ('ios', 'android', 'web'))
);

create index client_crash_reports_user_received
  on public.client_crash_reports (user_id, received_at desc);

alter table public.client_crash_reports enable row level security;

create policy "users_insert_own_crash_reports"
  on public.client_crash_reports
  for insert
  to authenticated
  with check (user_id = (select auth.uid()));

create policy "users_read_own_crash_reports"
  on public.client_crash_reports
  for select
  to authenticated
  using (user_id = (select auth.uid()));

grant select, insert on public.client_crash_reports to authenticated;
