import { PANTRY_CATALOG, type PantryCatalogCategory, type PantryCatalogItem } from './pantryCatalog';
import { getGeneratedCustomAsset } from './generatedAssetMap';

export type ResolvedItemAsset =
  | { kind: 'image'; source: any }
  | { kind: 'mdi'; name: string }
  | { kind: 'emoji'; value: string }
  | { kind: 'placeholder' };

// getGeneratedCustomAsset is generated by scripts/generate-asset-map.ts from
// every PNG under assets/custom-emojis/ and assets/item-icons/ — adding a new
// custom: icon is drop the PNG + `npm run assets:generate`, no edits here.
function getCustomEmojiSource(icon: string): any {
  return getGeneratedCustomAsset(icon);
}

// Icons for commonly typed items that are not in the catalog
const ITEM_ICON: Record<string, string> = {
  'hummus': '🫙', 'salsa': '🫙', 'guacamole': '🥑', 'ranch': '🫙',
  'ranch dressing': '🫙', 'bbq sauce': '🫙', 'sriracha': '🌶️',
  'teriyaki': '🫙', 'teriyaki sauce': '🫙', 'tahini': '🫙',
  'pesto': '🌿', 'marinara': '🍅', 'pasta sauce': '🍅', 'alfredo': '🫙',
  'baking soda': '🌾', 'baking powder': '🌾', 'vanilla extract': '🫙',
  'chocolate chips': '🍫', 'brown sugar': '🍬', 'cocoa powder': '🍫',
  'yeast': '🌾', 'cornstarch': '🌾',
  'beer': '🍺', 'wine': '🍷', 'vodka': '🥃', 'whiskey': '🥃',
  'kombucha': '🫙', 'iced tea': '🧃', 'lemonade': '🧃',
  'sweet potato': '🍠', 'yam': '🍠', 'mushroom': '🍄', 'mushrooms': '🍄',
  'jalapeño': '🌶️', 'jalapeno': '🌶️', 'zucchini': '🥒', 'asparagus': '🥦',
  'kale': '🥬', 'mango': '🥭', 'peach': '🍑', 'pear': '🍐',
  'cherry': '🍒', 'cherries': '🍒', 'pineapple': '🍍', 'coconut': '🥥',
  'kiwi': '🥝', 'grapefruit': '🍊', 'basil': '🌿', 'cilantro': '🌿',
  'parsley': '🌿', 'rosemary': '🌿', 'thyme': '🌿', 'dill': '🌿',
  'ham': '🥩', 'pork': '🥩', 'salami': '🥩', 'pepperoni': '🥩',
  'tofu': '🍱', 'tempeh': '🍱',
  'oysters': '🦪', 'clams': '🦪', 'scallops': '🦐',
  'broth': '🍲', 'chicken broth': '🍲', 'beef broth': '🍲',
  'vegetable broth': '🍲', 'stock': '🍲', 'coconut milk': '🥛',
  'sunscreen': '☀️', 'dental floss': '🦷', 'floss': '🦷',
  'mouthwash': '🫙', 'cotton balls': 'mdi:package-variant-closed', 'lip balm': '💄',
  'vitamins': '💊', 'ibuprofen': '💊', 'tylenol': '💊', 'aspirin': '💊',
  'protein powder': '💪', 'band aid': '🩹', 'bandaids': '🩹',
  'batteries': '🔋', 'light bulbs': '💡', 'candle': '🕯️',
  'air freshener': '🌺', 'matches': '🔥',

  // Common items with no dedicated catalog entry — closest safe existing icon
  'pepper': '🌶️', 'beef': '🥩', 'fish': '🐟', 'cream': '🫗',
  'berries': '🍓', 'soap': '🧼', 'bar soap': '🧼',
  'detergent': 'custom:laundry_detergent', 'foil': 'mdi:paper-roll-outline',
  'stock cube': '🍲', 'bouillon': '🍲', 'bouillon cube': '🍲',
  'mayo': '🫙',

  // Mission-required aliases/synonyms (targets already covered by the
  // catalog or the entries above — only the synonym itself is new here)
  'capsicum': '🫑',
  'coriander': '🌿',
  'scallion': '🧅', 'green onion': '🧅',
  'minced beef': '🥩',
  'soft drink': '🥤',
  'kitchen towel': '🧻',
};

// Safe per-category fallback — guarantees no blank box
const CATEGORY_ICON: Record<string, string> = {
  'Produce': '🥬', 'Dairy': '🥛', 'Meat': '🥩', 'Seafood': '🐟',
  'Bakery': '🍞', 'Frozen': '🧊', 'Dry Goods': '🌾', 'Canned': '🥫',
  'Spices': '🧂', 'Drinks': '🥤', 'Snacks': '🍿', 'Kitchen': '🍽️',
  'Cleaning': '🧹', 'Paper Goods': '🧻', 'Personal Care': '🧴',
  'Baby': '👶', 'Pet': '🐾', 'Other': '🛒',
  'Automotive': '🚗', 'Hardware': '🧰', 'Health': '💊', 'Office': 'mdi:paperclip',
};

// Lowercase, trim, collapse whitespace, and strip simple punctuation before
// any lookup — keeps matching resilient to how a name was typed.
export function normalizeForIcon(raw: string): string {
  return raw
    .trim()
    .toLowerCase()
    .replace(/[.,!?;:"'’]/g, '')
    .replace(/\s+/g, ' ');
}

// Tries an exact match first, then tolerates a simple trailing-"s" plural
// mismatch in either direction (input vs. stored key) without ever mangling
// words that merely end in "s" but aren't plural (e.g. "hummus").
function lookupTolerant<T>(map: Record<string, T>, normalized: string): T | undefined {
  if (map[normalized] !== undefined) return map[normalized];
  if (normalized.length > 4 && normalized.endsWith('s') && !normalized.endsWith('ss')) {
    const singular = normalized.slice(0, -1);
    if (map[singular] !== undefined) return map[singular];
  }
  const plural = `${normalized}s`;
  if (map[plural] !== undefined) return map[plural];
  return undefined;
}

const CATALOG_BY_NAME: Record<string, PantryCatalogItem> = {};
for (const catalogItem of PANTRY_CATALOG) {
  const key = normalizeForIcon(catalogItem.name);
  if (CATALOG_BY_NAME[key] === undefined) CATALOG_BY_NAME[key] = catalogItem;
}

/** Category of the closest curated catalog match for a free-text name, if any. */
export function lookupCatalogCategory(name: string): PantryCatalogCategory | undefined {
  return lookupTolerant(CATALOG_BY_NAME, normalizeForIcon(name))?.category;
}

/**
 * Deterministic icon-string resolution chain for a free-text item name:
 * curated catalog exact/alias match -> known alias table -> caller-supplied
 * fallback (e.g. itemClassifier's keyword guess) -> per-category safety net.
 * Never returns undefined — matches every existing render site's "no blank
 * box" guarantee.
 */
// Sentinel: catalog/alias entries use this generic mdi icon as a stand-in
// for "no real asset yet". Treat it as absent so the chain below falls
// through to the category-specific icon instead of showing it directly.
const NO_REAL_ASSET_SENTINEL = 'mdi:package-variant-closed';

function skipSentinel(icon: string | undefined): string | undefined {
  return icon && icon !== NO_REAL_ASSET_SENTINEL ? icon : undefined;
}

export function resolveItemIconString(name: string, fallbackEmoji?: string): string {
  const normalized = normalizeForIcon(name);
  const catalogItem = lookupTolerant(CATALOG_BY_NAME, normalized);
  const category = catalogItem?.category ?? 'Other';
  return (
    skipSentinel(catalogItem?.icon) ||
    skipSentinel(lookupTolerant(ITEM_ICON, normalized)) ||
    skipSentinel(fallbackEmoji) ||
    CATEGORY_ICON[category] ||
    CATEGORY_ICON.Other
  );
}

/** Parses a raw icon string (mdi:*, custom:*, or plain emoji) into a render-ready asset descriptor. */
export function resolveIconString(icon: string): ResolvedItemAsset {
  if (icon.startsWith('custom:')) {
    const source = getCustomEmojiSource(icon);
    return source ? { kind: 'image', source } : { kind: 'placeholder' };
  }
  if (icon.startsWith('mdi:')) {
    return { kind: 'mdi', name: icon.slice(4) };
  }
  return { kind: 'emoji', value: icon };
}

/** End-to-end: free-text item name -> render-ready asset descriptor. */
export function resolveItemAsset(name: string, fallbackEmoji?: string): ResolvedItemAsset {
  return resolveIconString(resolveItemIconString(name, fallbackEmoji));
}
